// Code generated by goctl. DO NOT EDIT!
// Source: resource.proto

package server

import (
	"context"

	"Pandax/panda-rpc/resource/internal/logic"
	"Pandax/panda-rpc/resource/internal/svc"
	"Pandax/panda-rpc/resource/resource"
)

type ResourceServer struct {
	svcCtx *svc.ServiceContext
}

func NewResourceServer(svcCtx *svc.ServiceContext) *ResourceServer {
	return &ResourceServer{
		svcCtx: svcCtx,
	}
}

func (s *ResourceServer) Ping(ctx context.Context, in *resource.Request) (*resource.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
