// Code generated by goctl. DO NOT EDIT!
// Source: develop.proto

package developclient

import (
	"context"

	"Pandax/panda-rpc/develop/develop"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = develop.Request
	Response = develop.Response

	Develop interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultDevelop struct {
		cli zrpc.Client
	}
)

func NewDevelop(cli zrpc.Client) Develop {
	return &defaultDevelop{
		cli: cli,
	}
}

func (m *defaultDevelop) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := develop.NewDevelopClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
