// Code generated by goctl. DO NOT EDIT!
// Source: job.proto

package server

import (
	"context"

	"Pandax/panda-rpc/job/internal/logic"
	"Pandax/panda-rpc/job/internal/svc"
	"Pandax/panda-rpc/job/job"
)

type JobServer struct {
	svcCtx *svc.ServiceContext
}

func NewJobServer(svcCtx *svc.ServiceContext) *JobServer {
	return &JobServer{
		svcCtx: svcCtx,
	}
}

func (s *JobServer) Ping(ctx context.Context, in *job.Request) (*job.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
