// Code generated by goctl. DO NOT EDIT!
// Source: system.proto

package systemclient

import (
	"context"

	"Pandax/panda-rpc/system/system"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = system.Request
	Response = system.Response

	System interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultSystem struct {
		cli zrpc.Client
	}
)

func NewSystem(cli zrpc.Client) System {
	return &defaultSystem{
		cli: cli,
	}
}

func (m *defaultSystem) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := system.NewSystemClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
